import { Sector } from '@/types';

export interface SectorWithRegion extends Sector {
  region: 'South Asia' | 'East Asia' | 'Middle East' | 'Europe' | 'Africa' | 'North America' | 'South America' | 'Oceania' | 'Polar';
}

export const SECTORS: SectorWithRegion[] = [
  /* SOUTH/SOUTHEAST ASIA - High monsoon activity */
  { name: "Mumbai", country: "IN", lat: 18.96, lon: 72.82, region: "South Asia" },
  { name: "Chennai", country: "IN", lat: 13.08, lon: 80.27, region: "South Asia" },
  { name: "Kolkata", country: "IN", lat: 22.57, lon: 88.36, region: "South Asia" },
  { name: "Delhi", country: "IN", lat: 28.67, lon: 77.22, region: "South Asia" },
  { name: "Bangalore", country: "IN", lat: 12.97, lon: 77.59, region: "South Asia" },
  { name: "Hyderabad", country: "IN", lat: 17.38, lon: 78.47, region: "South Asia" },
  { name: "Kochi", country: "IN", lat: 9.93, lon: 76.27, region: "South Asia" },
  { name: "Guwahati", country: "IN", lat: 26.18, lon: 91.74, region: "South Asia" },
  { name: "Bhubaneswar", country: "IN", lat: 20.27, lon: 85.84, region: "South Asia" },
  { name: "Thiruvananthapuram", country: "IN", lat: 8.52, lon: 76.94, region: "South Asia" },
  { name: "Dhaka", country: "BD", lat: 23.72, lon: 90.41, region: "South Asia" },
  { name: "Chittagong", country: "BD", lat: 22.34, lon: 91.83, region: "South Asia" },
  { name: "Colombo", country: "LK", lat: 6.93, lon: 79.85, region: "South Asia" },
  { name: "Kathmandu", country: "NP", lat: 27.72, lon: 85.32, region: "South Asia" },
  { name: "Karachi", country: "PK", lat: 24.86, lon: 67.01, region: "South Asia" },
  { name: "Lahore", country: "PK", lat: 31.55, lon: 74.35, region: "South Asia" },
  { name: "Bangkok", country: "TH", lat: 13.75, lon: 100.52, region: "South Asia" },
  { name: "Ho Chi Minh", country: "VN", lat: 10.82, lon: 106.63, region: "South Asia" },
  { name: "Hanoi", country: "VN", lat: 21.03, lon: 105.85, region: "South Asia" },
  { name: "Jakarta", country: "ID", lat: -6.21, lon: 106.85, region: "South Asia" },
  { name: "Surabaya", country: "ID", lat: -7.25, lon: 112.75, region: "South Asia" },
  { name: "Kuala Lumpur", country: "MY", lat: 3.14, lon: 101.69, region: "South Asia" },
  { name: "Manila", country: "PH", lat: 14.60, lon: 120.98, region: "South Asia" },
  { name: "Cebu", country: "PH", lat: 10.32, lon: 123.90, region: "South Asia" },
  { name: "Singapore", country: "SG", lat: 1.35, lon: 103.82, region: "South Asia" },
  { name: "Yangon", country: "MM", lat: 16.87, lon: 96.19, region: "South Asia" },
  { name: "Phnom Penh", country: "KH", lat: 11.55, lon: 104.92, region: "South Asia" },
  { name: "Vientiane", country: "LA", lat: 17.97, lon: 102.61, region: "South Asia" },

  /* EAST ASIA */
  { name: "Tokyo", country: "JP", lat: 35.69, lon: 139.69, region: "East Asia" },
  { name: "Osaka", country: "JP", lat: 34.69, lon: 135.50, region: "East Asia" },
  { name: "Seoul", country: "KR", lat: 37.57, lon: 126.98, region: "East Asia" },
  { name: "Busan", country: "KR", lat: 35.10, lon: 129.03, region: "East Asia" },
  { name: "Beijing", country: "CN", lat: 39.91, lon: 116.39, region: "East Asia" },
  { name: "Shanghai", country: "CN", lat: 31.23, lon: 121.47, region: "East Asia" },
  { name: "Guangzhou", country: "CN", lat: 23.13, lon: 113.26, region: "East Asia" },
  { name: "Chengdu", country: "CN", lat: 30.66, lon: 104.07, region: "East Asia" },
  { name: "Wuhan", country: "CN", lat: 30.58, lon: 114.27, region: "East Asia" },
  { name: "Hong Kong", country: "HK", lat: 22.32, lon: 114.17, region: "East Asia" },
  { name: "Taipei", country: "TW", lat: 25.04, lon: 121.57, region: "East Asia" },
  { name: "Ulaanbaatar", country: "MN", lat: 47.90, lon: 106.90, region: "East Asia" },

  /* CENTRAL ASIA & MIDDLE EAST */
  { name: "Dubai", country: "AE", lat: 25.20, lon: 55.27, region: "Middle East" },
  { name: "Riyadh", country: "SA", lat: 24.69, lon: 46.72, region: "Middle East" },
  { name: "Muscat", country: "OM", lat: 23.61, lon: 58.59, region: "Middle East" },
  { name: "Tehran", country: "IR", lat: 35.69, lon: 51.39, region: "Middle East" },
  { name: "Baghdad", country: "IQ", lat: 33.34, lon: 44.40, region: "Middle East" },
  { name: "Kabul", country: "AF", lat: 34.53, lon: 69.17, region: "Middle East" },
  { name: "Tashkent", country: "UZ", lat: 41.30, lon: 69.25, region: "Middle East" },
  { name: "Almaty", country: "KZ", lat: 43.26, lon: 76.95, region: "Middle East" },

  /* EUROPE */
  { name: "London", country: "GB", lat: 51.51, lon: -0.13, region: "Europe" },
  { name: "Manchester", country: "GB", lat: 53.48, lon: -2.24, region: "Europe" },
  { name: "Glasgow", country: "GB", lat: 55.86, lon: -4.25, region: "Europe" },
  { name: "Dublin", country: "IE", lat: 53.33, lon: -6.25, region: "Europe" },
  { name: "Paris", country: "FR", lat: 48.86, lon: 2.35, region: "Europe" },
  { name: "Marseille", country: "FR", lat: 43.30, lon: 5.37, region: "Europe" },
  { name: "Berlin", country: "DE", lat: 52.52, lon: 13.40, region: "Europe" },
  { name: "Hamburg", country: "DE", lat: 53.55, lon: 10.00, region: "Europe" },
  { name: "Munich", country: "DE", lat: 48.14, lon: 11.58, region: "Europe" },
  { name: "Amsterdam", country: "NL", lat: 52.37, lon: 4.90, region: "Europe" },
  { name: "Brussels", country: "BE", lat: 50.85, lon: 4.35, region: "Europe" },
  { name: "Madrid", country: "ES", lat: 40.42, lon: -3.70, region: "Europe" },
  { name: "Barcelona", country: "ES", lat: 41.39, lon: 2.15, region: "Europe" },
  { name: "Lisbon", country: "PT", lat: 38.72, lon: -9.14, region: "Europe" },
  { name: "Rome", country: "IT", lat: 41.90, lon: 12.50, region: "Europe" },
  { name: "Milan", country: "IT", lat: 45.46, lon: 9.19, region: "Europe" },
  { name: "Venice", country: "IT", lat: 45.44, lon: 12.33, region: "Europe" },
  { name: "Vienna", country: "AT", lat: 48.21, lon: 16.37, region: "Europe" },
  { name: "Zurich", country: "CH", lat: 47.38, lon: 8.54, region: "Europe" },
  { name: "Warsaw", country: "PL", lat: 52.23, lon: 21.01, region: "Europe" },
  { name: "Stockholm", country: "SE", lat: 59.33, lon: 18.07, region: "Europe" },
  { name: "Oslo", country: "NO", lat: 59.91, lon: 10.75, region: "Europe" },
  { name: "Bergen", country: "NO", lat: 60.39, lon: 5.32, region: "Europe" },
  { name: "Copenhagen", country: "DK", lat: 55.68, lon: 12.57, region: "Europe" },
  { name: "Helsinki", country: "FI", lat: 60.17, lon: 24.94, region: "Europe" },
  { name: "Athens", country: "GR", lat: 37.98, lon: 23.73, region: "Europe" },
  { name: "Istanbul", country: "TR", lat: 41.01, lon: 28.95, region: "Europe" },
  { name: "Kyiv", country: "UA", lat: 50.45, lon: 30.52, region: "Europe" },
  { name: "Moscow", country: "RU", lat: 55.75, lon: 37.62, region: "Europe" },
  { name: "St. Petersburg", country: "RU", lat: 59.95, lon: 30.32, region: "Europe" },

  /* AFRICA */
  { name: "Lagos", country: "NG", lat: 6.46, lon: 3.38, region: "Africa" },
  { name: "Abuja", country: "NG", lat: 9.06, lon: 7.50, region: "Africa" },
  { name: "Accra", country: "GH", lat: 5.56, lon: -0.21, region: "Africa" },
  { name: "Nairobi", country: "KE", lat: -1.29, lon: 36.82, region: "Africa" },
  { name: "Mombasa", country: "KE", lat: -4.05, lon: 39.67, region: "Africa" },
  { name: "Dar es Salaam", country: "TZ", lat: -6.79, lon: 39.21, region: "Africa" },
  { name: "Kampala", country: "UG", lat: 0.32, lon: 32.59, region: "Africa" },
  { name: "Addis Ababa", country: "ET", lat: 9.03, lon: 38.74, region: "Africa" },
  { name: "Kinshasa", country: "CD", lat: -4.33, lon: 15.32, region: "Africa" },
  { name: "Dakar", country: "SN", lat: 14.69, lon: -17.45, region: "Africa" },
  { name: "Abidjan", country: "CI", lat: 5.35, lon: -4.00, region: "Africa" },
  { name: "Douala", country: "CM", lat: 4.05, lon: 9.70, region: "Africa" },
  { name: "Luanda", country: "AO", lat: -8.84, lon: 13.23, region: "Africa" },
  { name: "Johannesburg", country: "ZA", lat: -26.20, lon: 28.04, region: "Africa" },
  { name: "Cape Town", country: "ZA", lat: -33.92, lon: 18.42, region: "Africa" },
  { name: "Durban", country: "ZA", lat: -29.85, lon: 31.02, region: "Africa" },
  { name: "Khartoum", country: "SD", lat: 15.55, lon: 32.53, region: "Africa" },
  { name: "Cairo", country: "EG", lat: 30.06, lon: 31.25, region: "Africa" },
  { name: "Casablanca", country: "MA", lat: 33.59, lon: -7.62, region: "Africa" },
  { name: "Tunis", country: "TN", lat: 36.82, lon: 10.18, region: "Africa" },
  { name: "Antananarivo", country: "MG", lat: -18.91, lon: 47.54, region: "Africa" },

  /* NORTH AMERICA */
  { name: "New York", country: "US", lat: 40.71, lon: -74.01, region: "North America" },
  { name: "Los Angeles", country: "US", lat: 34.05, lon: -118.24, region: "North America" },
  { name: "Chicago", country: "US", lat: 41.88, lon: -87.63, region: "North America" },
  { name: "Houston", country: "US", lat: 29.76, lon: -95.37, region: "North America" },
  { name: "Miami", country: "US", lat: 25.77, lon: -80.19, region: "North America" },
  { name: "Seattle", country: "US", lat: 47.61, lon: -122.33, region: "North America" },
  { name: "New Orleans", country: "US", lat: 29.95, lon: -90.07, region: "North America" },
  { name: "Denver", country: "US", lat: 39.74, lon: -104.98, region: "North America" },
  { name: "Phoenix", country: "US", lat: 33.45, lon: -112.07, region: "North America" },
  { name: "Atlanta", country: "US", lat: 33.75, lon: -84.39, region: "North America" },
  { name: "Boston", country: "US", lat: 42.36, lon: -71.06, region: "North America" },
  { name: "Dallas", country: "US", lat: 32.79, lon: -96.80, region: "North America" },
  { name: "Toronto", country: "CA", lat: 43.65, lon: -79.38, region: "North America" },
  { name: "Vancouver", country: "CA", lat: 49.25, lon: -123.12, region: "North America" },
  { name: "Montreal", country: "CA", lat: 45.50, lon: -73.57, region: "North America" },
  { name: "Mexico City", country: "MX", lat: 19.43, lon: -99.13, region: "North America" },
  { name: "Guadalajara", country: "MX", lat: 20.66, lon: -103.35, region: "North America" },
  { name: "Havana", country: "CU", lat: 23.13, lon: -82.38, region: "North America" },
  { name: "Panama City", country: "PA", lat: 8.99, lon: -79.52, region: "North America" },

  /* SOUTH AMERICA */
  { name: "São Paulo", country: "BR", lat: -23.55, lon: -46.63, region: "South America" },
  { name: "Rio de Janeiro", country: "BR", lat: -22.91, lon: -43.17, region: "South America" },
  { name: "Manaus", country: "BR", lat: -3.10, lon: -60.02, region: "South America" },
  { name: "Belém", country: "BR", lat: -1.46, lon: -48.50, region: "South America" },
  { name: "Recife", country: "BR", lat: -8.06, lon: -34.88, region: "South America" },
  { name: "Buenos Aires", country: "AR", lat: -34.60, lon: -58.38, region: "South America" },
  { name: "Lima", country: "PE", lat: -12.05, lon: -77.04, region: "South America" },
  { name: "Bogotá", country: "CO", lat: 4.71, lon: -74.07, region: "South America" },
  { name: "Medellín", country: "CO", lat: 6.22, lon: -75.57, region: "South America" },
  { name: "Caracas", country: "VE", lat: 10.49, lon: -66.88, region: "South America" },
  { name: "Quito", country: "EC", lat: -0.23, lon: -78.52, region: "South America" },
  { name: "Santiago", country: "CL", lat: -33.46, lon: -70.65, region: "South America" },

  /* OCEANIA */
  { name: "Sydney", country: "AU", lat: -33.87, lon: 151.21, region: "Oceania" },
  { name: "Melbourne", country: "AU", lat: -37.81, lon: 144.96, region: "Oceania" },
  { name: "Brisbane", country: "AU", lat: -27.47, lon: 153.03, region: "Oceania" },
  { name: "Darwin", country: "AU", lat: -12.46, lon: 130.84, region: "Oceania" },
  { name: "Auckland", country: "NZ", lat: -36.87, lon: 174.77, region: "Oceania" },
  { name: "Wellington", country: "NZ", lat: -41.29, lon: 174.78, region: "Oceania" },
  { name: "Port Moresby", country: "PG", lat: -9.44, lon: 147.18, region: "Oceania" },
  { name: "Fiji (Suva)", country: "FJ", lat: -18.14, lon: 178.44, region: "Oceania" },

  /* POLAR / REMOTE */
  { name: "Reykjavik", country: "IS", lat: 64.13, lon: -21.94, region: "Polar" },
  { name: "Anchorage", country: "US", lat: 61.22, lon: -149.90, region: "Polar" },
  { name: "Fairbanks", country: "US", lat: 64.84, lon: -147.72, region: "Polar" },
  { name: "Tromsø", country: "NO", lat: 69.65, lon: 18.95, region: "Polar" },
  { name: "Nuuk", country: "GL", lat: 64.18, lon: -51.74, region: "Polar" }
];
