import os
import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

SUMO_DIR = Path(__file__).resolve().parent
SCRIPTS_DIR = Path(os.path.expanduser("~")) / "AppData" / "Roaming" / "Python" / "Python313" / "Scripts"
SUMO_BINARY = str(SCRIPTS_DIR / "sumo.exe") if (SCRIPTS_DIR / "sumo.exe").exists() else "sumo"

def run_scenario(config_file: str, prefix: str):
    tripinfo_file = SUMO_DIR / f"{prefix}_tripinfo.xml"
    summary_file = SUMO_DIR / f"{prefix}_summary.xml"
    
    cmd = [
        SUMO_BINARY,
        "-c", str(SUMO_DIR / config_file),
        "--tripinfo-output", str(tripinfo_file),
        "--summary-output", str(summary_file),
        "--no-step-log", "true",
        "--duration-log.disable", "true",
    ]
    
    env = os.environ.copy()
    env["PATH"] = f"{SCRIPTS_DIR};{env.get('PATH', '')}"
    
    res = subprocess.run(cmd, capture_output=True, text=True, env=env)
    if res.returncode != 0:
        raise RuntimeError(f"SUMO simulation failed: {res.stderr}")
    
    # Parse tripinfo XML generated by SUMO
    tree = ET.parse(tripinfo_file)
    root = tree.getroot()
    trips = root.findall("tripinfo")
    
    if not trips:
        return {"travel_time_s": 0.0, "time_loss_s": 0.0, "route_length_m": 0.0, "vehicles": 0}
    
    total_duration = sum(float(t.get("duration", 0)) for t in trips)
    total_time_loss = sum(float(t.get("timeLoss", 0)) for t in trips)
    total_length = sum(float(t.get("routeLength", 0)) for t in trips)
    n = len(trips)
    
    return {
        "travel_time_s": round(total_duration / n, 2),
        "time_loss_s": round(total_time_loss / n, 2),
        "route_length_m": round(total_length / n, 2),
        "vehicles": n,
    }

def main():
    baseline = run_scenario("pilot_baseline.sumocfg", "baseline")
    flooded = run_scenario("pilot_flooded.sumocfg", "flooded")
    
    print("=== SUMO REAL SIMULATION RUNNER OUTPUT ===")
    print(f"Metric | Normal | Flood Event")
    print(f"Travel time: {baseline['travel_time_s']}s -> {flooded['travel_time_s']}s")
    print(f"Congestion (Time Loss): {baseline['time_loss_s']}s -> {flooded['time_loss_s']}s")
    print(f"Average Route Length: {baseline['route_length_m']}m -> {flooded['route_length_m']}m")
    print(f"Vehicles Simulated: {baseline['vehicles']} -> {flooded['vehicles']}")
    print(f"Affected edges: 3 (street_segment_02 inundated; bypass_edge_01 & bypass_edge_02 active)")
    
    return baseline, flooded

if __name__ == "__main__":
    main()
